// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/11/2024, 13:39:31
const configMerger = require("C:/Users/josip/Documents/dev/_cloned website/PortfolioJosipa/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/josip/Documents/dev/_cloned website/PortfolioJosipa/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/josip/Documents/dev/_cloned website/PortfolioJosipa/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/josip/Documents/dev/_cloned website/PortfolioJosipa/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/josip/Documents/dev/_cloned website/PortfolioJosipa/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/josip/Documents/dev/_cloned website/PortfolioJosipa/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/josip/Documents/dev/_cloned website/PortfolioJosipa/plugins/**/*.{js,ts,mjs}","C:/Users/josip/Documents/dev/_cloned website/PortfolioJosipa/composables/**/*.{js,ts,mjs}","C:/Users/josip/Documents/dev/_cloned website/PortfolioJosipa/utils/**/*.{js,ts,mjs}","C:/Users/josip/Documents/dev/_cloned website/PortfolioJosipa/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/josip/Documents/dev/_cloned website/PortfolioJosipa/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/josip/Documents/dev/_cloned website/PortfolioJosipa/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["23"] = "C:/Users/josip/Documents/dev/_cloned website/PortfolioJosipa/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})()
